"use client";

import React from 'react';
import Image from 'next/image';
import { BrainCircuit } from 'lucide-react';

interface ReportDocumentProps {
  imagePreview: string | null;
  probability: number;
  disclaimer: string;
}

const getStatusInfo = (probability: number) => {
    const percentage = Math.round(probability);
    if (percentage < 1) {
        return { text: 'No Tumor Detected', color: 'text-blue-600' };
    }
    if (percentage >= 75) {
        return { text: 'High Probability', color: 'text-red-600' };
    }
    if (percentage >= 50) {
        return { text: 'Moderate Probability', color: 'text-orange-500' };
    }
    return { text: 'Low Probability', color: 'text-blue-600' };
};


export const ReportDocument = React.forwardRef<HTMLDivElement, ReportDocumentProps>(
  ({ imagePreview, probability, disclaimer }, ref) => {
    
    const statusInfo = getStatusInfo(probability);
    const analysisDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });

    return (
        <div ref={ref} className="p-10 font-sans bg-white text-gray-800" style={{width: '210mm', minHeight: '297mm'}}>
          {/* Header */}
          <div className="flex justify-between items-center pb-4 border-b-2 border-gray-200">
            <div className="flex items-center gap-3">
                <BrainCircuit className="h-10 w-10 text-blue-600" />
                <h1 className="text-3xl font-bold text-gray-800">BrainScan AI Analysis Report</h1>
            </div>
            <div className="text-right">
                <p className="text-sm">Date of Analysis</p>
                <p className="font-semibold">{analysisDate}</p>
            </div>
          </div>

          {/* Main Content */}
          <div className="mt-8 grid grid-cols-2 gap-8">
            {/* Left Column: Image */}
            <div className="space-y-4">
              <h2 className="text-xl font-semibold border-b pb-2">Uploaded MRI Scan</h2>
              <div className="w-full aspect-square relative border-2 border-gray-300 rounded-lg overflow-hidden">
                {imagePreview && (
                  <Image
                    src={imagePreview}
                    alt="Uploaded MRI scan"
                    layout="fill"
                    objectFit="cover"
                  />
                )}
              </div>
            </div>

            {/* Right Column: Results */}
            <div className="space-y-6">
              <h2 className="text-xl font-semibold border-b pb-2">Analysis Results</h2>
              <div className="p-4 bg-gray-50 rounded-lg border border-gray-200">
                <p className="text-sm text-gray-600">Tumor Probability Score</p>
                <p className={`text-6xl font-bold ${statusInfo.color}`}>{Math.round(probability)}%</p>
                <p className={`text-lg font-semibold mt-1 ${statusInfo.color}`}>{statusInfo.text}</p>
              </div>
              
              <div>
                  <h3 className="font-semibold text-lg">Disclaimer</h3>
                  <p className="text-sm mt-1 text-gray-600 bg-yellow-50 border border-yellow-200 p-3 rounded-lg">{disclaimer}</p>
              </div>
            </div>
          </div>
          
          {/* Footer */}
          <div className="mt-12 pt-4 border-t-2 border-gray-200 text-center text-xs text-gray-500">
            <p>This report was generated by BrainScan AI. It is not a substitute for professional medical advice, diagnosis, or treatment.</p>
            <p>&copy; {new Date().getFullYear()} BrainScan AI. All rights reserved.</p>
          </div>
        </div>
    );
  }
);

ReportDocument.displayName = 'ReportDocument';
